# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 591)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(".MainWindow {\n"
"     \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_group_box.sizePolicy().hasHeightForWidth())
        self.url_group_box.setSizePolicy(sizePolicy)
        self.url_group_box.setStyleSheet("#url_group_box {\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.url_group_box.setObjectName("url_group_box")
        self.url_input_layout = QtWidgets.QHBoxLayout(self.url_group_box)
        self.url_input_layout.setContentsMargins(3, -1, 3, -1)
        self.url_input_layout.setObjectName("url_input_layout")
        self.url = QtWidgets.QLabel(self.url_group_box)
        self.url.setStyleSheet("padding: 5px;\n"
"padding-right: 0px;")
        self.url.setObjectName("url")
        self.url_input_layout.addWidget(self.url)
        self.url_input = QtWidgets.QLineEdit(self.url_group_box)
        self.url_input.setStyleSheet("margin-right: 5px;")
        self.url_input.setObjectName("url_input")
        self.url_input_layout.addWidget(self.url_input)
        self.verticalLayout.addWidget(self.url_group_box)
        self.video_info_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.video_info_group_box.setStyleSheet("#video_info_group_box {\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.video_info_group_box.setObjectName("video_info_group_box")
        self.video_info_layout = QtWidgets.QVBoxLayout(self.video_info_group_box)
        self.video_info_layout.setContentsMargins(10, 10, 10, 10)
        self.video_info_layout.setSpacing(10)
        self.video_info_layout.setObjectName("video_info_layout")
        self.video_thumbnail = QtWidgets.QLabel(self.video_info_group_box)
        self.video_thumbnail.setMinimumSize(QtCore.QSize(1, 1))
        self.video_thumbnail.setStyleSheet("")
        self.video_thumbnail.setText("")
        self.video_thumbnail.setPixmap(QtGui.QPixmap("img/Youtube.png"))
        self.video_thumbnail.setScaledContents(False)
        self.video_thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.video_thumbnail.setObjectName("video_thumbnail")
        self.video_info_layout.addWidget(self.video_thumbnail)
        self.video_title = QtWidgets.QLabel(self.video_info_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_title.sizePolicy().hasHeightForWidth())
        self.video_title.setSizePolicy(sizePolicy)
        self.video_title.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"padding: 1px;")
        self.video_title.setObjectName("video_title")
        self.video_info_layout.addWidget(self.video_title)
        self.verticalLayout.addWidget(self.video_info_group_box)
        self.save_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_group_box.sizePolicy().hasHeightForWidth())
        self.save_group_box.setSizePolicy(sizePolicy)
        self.save_group_box.setStyleSheet("#save_group_box {\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.save_group_box.setFlat(False)
        self.save_group_box.setCheckable(False)
        self.save_group_box.setObjectName("save_group_box")
        self.save_layout = QtWidgets.QVBoxLayout(self.save_group_box)
        self.save_layout.setContentsMargins(10, 10, 10, 10)
        self.save_layout.setSpacing(10)
        self.save_layout.setObjectName("save_layout")
        self.save_select_layout = QtWidgets.QHBoxLayout()
        self.save_select_layout.setSpacing(3)
        self.save_select_layout.setObjectName("save_select_layout")
        self.download_choose = QtWidgets.QComboBox(self.save_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_choose.sizePolicy().hasHeightForWidth())
        self.download_choose.setSizePolicy(sizePolicy)
        self.download_choose.setObjectName("download_choose")
        self.save_select_layout.addWidget(self.download_choose)
        self.file_name_label = QtWidgets.QLabel(self.save_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_name_label.sizePolicy().hasHeightForWidth())
        self.file_name_label.setSizePolicy(sizePolicy)
        self.file_name_label.setStyleSheet("padding-left: 25px;\n"
"")
        self.file_name_label.setText("")
        self.file_name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_name_label.setObjectName("file_name_label")
        self.save_select_layout.addWidget(self.file_name_label)
        self.save_button = QtWidgets.QPushButton(self.save_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setObjectName("save_button")
        self.save_select_layout.addWidget(self.save_button)
        self.save_layout.addLayout(self.save_select_layout)
        self.progress_bar = QtWidgets.QProgressBar(self.save_group_box)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.save_layout.addWidget(self.progress_bar)
        self.verticalLayout.addWidget(self.save_group_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuLanguage = QtWidgets.QMenu(self.menuBar)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menuBar)
        self.action_english = QtWidgets.QAction(MainWindow)
        self.action_english.setObjectName("action_english")
        self.action_ukraine = QtWidgets.QAction(MainWindow)
        self.action_ukraine.setObjectName("action_ukraine")
        self.menuLanguage.addAction(self.action_english)
        self.menuLanguage.addAction(self.action_ukraine)
        self.menuBar.addAction(self.menuLanguage.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoutubeDownloader"))
        self.url_group_box.setTitle(_translate("MainWindow", "1. Type video URL and press Enter"))
        self.url.setText(_translate("MainWindow", "URL:"))
        self.video_info_group_box.setTitle(_translate("MainWindow", "2. Wait until program found video"))
        self.video_title.setText(_translate("MainWindow", "Type URL"))
        self.save_group_box.setTitle(_translate("MainWindow", "3. Select video/audio resolution and click save button"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.action_english.setText(_translate("MainWindow", "English"))
        self.action_ukraine.setText(_translate("MainWindow", "Ukraine"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
